# meta/main.yml
---
galaxy_info:
  role_name: haproxy
  author: leshevi
  description: A role for installing haproxy
  license: license (GPLv3, MIT, etc)
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - haproxy
dependencies: []
